// map = [
//   [6, "white"],
//   [4, "white"],
//   [2, "white"],
//   [2, "white"],
//   [1, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0],
//   [0],
//   [4, "black"],
//   [0, "white"],
//   [0],
//   [0],
//   [0],
//   [4, "black"],
//   [0],
//   [5, "black"],
//   [0, "white"],
//   [0],
//   [0],
//   [0, "white"],
//   [0, "white"],
//   [1, "black"],
//   [0, "white"],
//   [0, "black"],
//   [0, "white"],
// ];

// map = [
//   [1, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0, "white"],
//   [0],
//   [0],
//   [4, "black"],
//   [0, "white"],
//   [0],
//   [0],
//   [0],
//   [4, "black"],
//   [0],
//   [5, "black"],
//   [0, "white"],
//   [0],
//   [0],
//   [0, "white"],
//   [0, "white"],
//   [1, "black"],
//   [0, "white"],
//   [0, "black"],
//   [15, "white"],
// ];
